version: "3.9"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
     - /home/maxime/Desktop/envs/.env.staging
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres