FROM node:16.14.0-alpine As production

WORKDIR /usr/src/mizipets

COPY package*.json ./

RUN npm ci

RUN npm i -g @nestjs/cli

COPY . .

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002

CMD [ "npm", "run", "start:staging" ]
