version: "3.9"
services:
  api:
    build: .
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - mizipetsnetwork
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - mizipetsnetwork

volumes:
  database:

networks:
  mizipetsnetwork:
    driver: bridge