name:  Deploy api prod

on:
   release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd mizipets-api
          docker-compose stop
          git checkout master
          docker rm -f mizipets-api_api_1
          docker rmi -f mizipets-api_api_1
          docker compose pull front
          git pull
          rm -rf envs
          mkdir envs
          cp ~/.env.prod ./envs/.env.prod
          cp ~/.env.local ./envs/.env.local
          docker-compose up -d --build --env-file ./.compose/.env.prod