name: Deploy staging

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ubuntu
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd mizipets-api
          docker-compose down
          git pull
          rm -rf envs
          mkdir envs
          echo ${{secrets.STAGING_ENV}} > envs/.env.staging
          docker-compose up -d --build
          npm run seed:run