name: Deploy api staging

on: 
  workflow_dispatch:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd mizipets-api
          docker compose -f docker-compose.staging.yml stop
          git checkout master
          docker rm -f mizipets-api_api_1
          docker rmi -f mizipets-api_api_1
          docker compose pull front
          git pull
          rm -rf envs
          mkdir envs
          cp ~/.env.staging ./envs/.env.staging
          cp ~/.env.local ./envs/.env.local
          docker compose -f docker-compose.staging.yml up -d --build
