name: Deploy staging

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
    - run: echo "Print"
    - run:  echo ${{ secrets.STAGING_HOST }}
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ubuntu
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd mizipets-api
          docker-compose down
          git pull
          docker-compose up -d --build