name: Deploy staging

on: 
  workflow_dispatch:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd mizipets-api
          docker-compose down
          docker rm -f mizipets-api_api
          docker rmi -f mizipets-api_api
          git pull
          rm -rf envs
          mkdir envs
          cp ~/.env.staging ./envs/.env.staging
          cp ~/.env.local ./envs/.env.local
          docker-compose up -d --build