name: Deploy staging

on: 
  workflow_dispatch:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_USER }}
          SSH_KEY: ${{ secrets.STAGING_KEY }}
          SSH_HOST: ${{ secrets.STAGING_HOST }}
      - name: Deploy
        run: |
          ssh staging 'ls -la'
        # cd mizipets-api
        # docker-compose down
        # docker rm -f $(docker ps -qa)
        # docker rmi -f $(docker images -aq)
        # git pull
        # rm -rf envs
        # mkdir envs
        # cp ~/.env.staging ./envs/.env.staging
        # cp ~/.env.local ./envs/.env.local
        # docker-compose up -d --build
      # uses: appleboy/ssh-action@master
      # with:
      #   host: ${{ secrets.STAGING_HOST }}
      #   username: api
      #   key: ${{ secrets.STAGING_KEY }}
      #   port: 22
      #   script: |
      #     cd mizipets-api
      #     docker-compose down
      #     docker rm -f $(docker ps -qa)
      #     docker rmi -f $(docker images -aq)
      #     git pull
      #     rm -rf envs
      #     mkdir envs
      #     cp ~/.env.staging ./envs/.env.staging
      #     cp ~/.env.local ./envs/.env.local
      #     docker-compose up -d --build